### ISSUE TITLE
Rewrite based on Prettier Rules

### ISSUE THREAD

**Issue by jpx40** [bram209/leptosfmt#100]
Hey, started to play a little bit around with the source code. I noticed that still a lot of stuff missing, i mean the rules aren't very strict (stuff like line breaks of tags on the same level). I am currently in an learning process of stuff like traits and macros is new for me. I want to ask if you are interested in an rewrite of the Rule set based prettier (basically port prettier to Rust). I would to offer my help.

**Comment by bram209** [comment]
Hi, I am open to contributions. I propose that you create specific issues for formatting rules that you would like to behave differently. Also, note that, through prettier can be a great reference, the aim of this library is not to match its exact behavior.

I will close this issue, as it is not very actionable, but like I said, feel free to request changes through Github issues : )
