### ISSUE TITLE
Remove multiple spaces and format multiline for string attributes

### ISSUE THREAD

**Issue by cedeber** [bram209/leptosfmt#103]
That can be done for all attributes but I think the most useful case could be the `class` attribute.

First example is:
```html
<div class="too     much    spaces" />
```
or, especially useful with Tailwind craziness:
```html
<button class="flex justify-center rounded-md bg-indigo-600 px-3 py-1.5 text-sm font-semibold leading-6	text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2  focus-visible:outline-indigo-600">
Click me
</button>
```
could be
```html
<button
	class="flex justify-center rounded-md bg-indigo-600 px-3 py-1.5 text-sm font-semibold leading-6
	text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 
	focus-visible:outline-offset-2  focus-visible:outline-indigo-600"
>
```

**Comment by bram209** [comment]
I am not sure that we can blindly do this for arbitrary attribute values? Sometimes the spacing might be intended, I don't we should make that assumption tbh.

As for formatting tailwind classes, have you looked at #14 ?

**Comment by bram209** [comment]
closing this, feel free to reopen if above suggestion is not workable for you
