### ISSUE TITLE
Load configuration from `leptosfmt.toml`

### ISSUE THREAD

**Issue by bram209** [bram209/leptosfmt#11]

**Comment by rakshith-ravi** [comment]
Mind if I take this up? Seems simple enough for me to get a start on the code-base

**Comment by bram209** [comment]
Hi, that would be nice!

I think we can start small and serde with toml deserialization will suffice. We can use https://serde.rs/container-attrs.html#default attribute on the FormattingSettings and add a `--config-file` option to the CLI.

If you need anything, ask away!
