### ISSUE TITLE
Allow a `--check` mode, to verify formatting is correct

### ISSUE THREAD

**Issue by roboteng** [bram209/leptosfmt#12]
Similar to `cargo fmt` where if `--check` is passed, then if anything needs to be formatted, the program exits with a non-zero exit code, indicating that the formatting was not correct.

**Comment by roboteng** [comment]
I was thinking of starting this, but wanted to make an issue first to track things

**Comment by bram209** [comment]
Hi, sounds good, this will be handy for CI : )
Let me know if you need anything!

**Comment by dessalines** [comment]
As a temporary workaround, you can do something like:

```
cp -R src /tmp/my_src
leptosfmt src
diff /tmp/my_src src
```

This fails for me currently tho due to #42
