### ISSUE TITLE
New release but with old version number

### ISSUE THREAD

**Issue by johansmitsnl** [bram209/leptosfmt#131]
The new `0.1.30` still reports as version `0.1.20`. I guess you forgot to update: https://github.com/bram209/leptosfmt/blob/c8b22bbeb67f17d3b78333566b366c528593c817/Cargo.toml#L6

**Comment by bram209** [comment]
Hi, unfortunately something went wrong when deploying (I should automate this...) and I was left with some staged changes in my git repository : (

The packaged release in `crates.io` has the correct source attached to it, though. Fixed now, thanks for notifying me!
