### ISSUE TITLE
`leptosfmt` removes comment from formatted `view!` when it's the first line

### ISSUE THREAD

**Issue by spencewenski** [bram209/leptosfmt#137]
I noticed that `leptosfmt` removes comments from the `view!` macro, but seemingly only when the comment is on the first line. If a comment appears elsewhere in the macro, `leptosfmt` doesn't remove it.

In the below screen recording, the comment is removed after pressing Cmd + S

https://github.com/user-attachments/assets/3068acf8-da43-4cf5-9387-17b7925c352a

```shell
[grqmuxsirm] 01:46 ~> leptosfmt --version
leptosfmt 0.1.20
[grqmuxsirm] 01:46 ~> rustc --version
rustc 1.80.0 (051478957 2024-07-21)
[grqmuxsirm] 01:46 ~> cargo --version
cargo 1.80.0 (376290515 2024-07-16)
```

**Comment by bram209** [comment]
Hi, thank you for the bug report. There is a test case that tests exactly this, so I am a bit surprised that it strips away the comment: https://github.com/bram209/leptosfmt/blob/d1304ea9b77f9e9abff4c3201dcdf1b6c9126815/formatter/src/source_file.rs#L353

Until this is fixed, I recommend putting the comment above the `view! { .. }` expression.

**Comment by spencewenski** [comment]
I wonder if the `cx` on the same line as the `view! {’ makes it so the comment isn’t actually on the first line, in which case that test isn’t actually testing first-line comments.

**Comment by bram209** [comment]
Ah, you probably are right.

**Comment by rashack** [comment]
A comment is also removed if it's the last line in a view macro.
```
$ leptosfmt --version
leptosfmt 0.1.30
```
