### ISSUE TITLE
Feature request: preserve comments

### ISSUE THREAD

**Issue by elliotwaite** [bram209/leptosfmt#15]
The formatter currently removes comments. It would be nice to have the option to preserve comments (or perhaps this could be made the default behavior).

**Comment by bram209** [comment]
duplicate of #3

**Comment by elliotwaite** [comment]
Ah, got it, thanks.

Sorry for forgetting to check for duplicates before posting this. I'll make sure to do so in the future.

**Comment by bram209** [comment]
No problem! L
