### ISSUE TITLE
panic at self closing div or path

### ISSUE THREAD

**Issue by johansmitsnl** [bram209/leptosfmt#50]
When you have a self closing `div` or a `path` in case of a svg the formater panics.

```rs
view! { cx,
    <Suspense fallback=move || view! { cx, <Loading/> }>
      <div class="mt-16 lg:mt-12"/>
    </Suspense>
}
```

I run version `0.1.10`

**Comment by dessalines** [comment]
I'm also getting this. Test cases should probably be added for the fix as well.

**Comment by bram209** [comment]
could you try the latest version from git?

**Comment by bram209** [comment]
cargo install --git https://github.com/bram209/leptosfmt.git

**Comment by dessalines** [comment]
@bram209 the git version is working correctly.
