### ISSUE TITLE
Compatibility with Leptos 0.5.x

### ISSUE THREAD

**Issue by PaulWagener** [bram209/leptosfmt#51]
Leptosfmt is currently not compatible with the new [0.5.0-alpha ](https://github.com/leptos-rs/leptos/releases/tag/v0.5.0-alpha)release.
A major change in this version is that the Scope and all corresponding `cx` argument passing has been removed. The new `view!` macro does not take a Scope anymore:

````rust
view! {
    <p>Hello</p>
}
````

Leptosfmt does not recognize this format and fails to format this view macro

**Comment by bram209** [comment]
oh cool DX improvement, I guess I should put this behind a flag in the configuration, so that people have time to migrate.
