### ISSUE TITLE
Bad indentation

### ISSUE THREAD

**Issue by awesomelemonade** [bram209/leptosfmt#58]
Rustfmt yields
```rust
use leptos::*;

fn test2(cx: Scope) -> impl IntoView {
    let x = vec![1]
        .into_iter()
        .map(|i| {
            view! { cx,
                <div>

                    {move || { i }}

                </div>
            }
        })
        .collect_view(cx);
    let z = view! { cx,
        <div>

            {move || { 0 }}

        </div>
    };
    view! { cx, <div>{x}</div> }
}
```
Running leptosfmt 0.1.11 afterwards yields
```rust
use leptos::*;

fn test2(cx: Scope) -> impl IntoView {
    let x = vec![1]
        .into_iter()
        .map(|i| {
            view! { cx,
            <div>

                {move || { i }}

            </div>
        }
        })
        .collect_view(cx);
    let z = view! { cx,
            <div>

                {move || { 0 }}

            </div>
        };
    view! { cx, <div>{x}</div> }
}

```

We can see that the first view! leptosfmt actively unindents it while in the second view! it indents it even further

**Comment by johansmitsnl** [comment]
This is the same issue as #54

**Comment by awesomelemonade** [comment]
> This is the same issue as #54

I think it's slightly different, and that this example is a more-minimal example. The example provided in #54 works just fine on my IDE. I have both rustfmt and leptosfmt on default settings (4 spaces). In the example above, it only breaks when view! is nested in some closure (such as map).

**Comment by awesomelemonade** [comment]
See https://github.com/bram209/leptosfmt/issues/54#issuecomment-1656851413

**Comment by bram209** [comment]
@awesomelemonade  can you try `cargo install --git https://github.com/bram209/leptosfmt.git --branch fix-view-indentation-issues` and let me know if that fixes your problem?

**Comment by awesomelemonade** [comment]
looks good to me, thanks!
