### ISSUE TITLE
leptosfmt generates incorrect HTML

### ISSUE THREAD

**Issue by srid** [bram209/leptosfmt#62]
For example,

![image](https://github.com/bram209/leptosfmt/assets/3998/ec2f0b55-c1c7-41e0-a24e-5c79e2ce7af8)

(Note the `y">` before Loading)

To repro, run leptosfmt in https://github.com/juspay/nix-browser/blob/07f1b187fea776f0ea9a22224aab5f5d5960c280/src/app.rs

**Comment by bram209** [comment]
most likely caused by: https://github.com/dtolnay/proc-macro2/issues/410
