### ISSUE TITLE
When parsing errors, return the stdin instead of an empty string with the `--stdin`

### ISSUE THREAD

**Issue by gawlk** [bram209/leptosfmt#75]
It breaks format pipelines (in my editor for example) by wiping the content of the whole file since the `leptosfmt` pipe returns an empty string.

It's only with the `--stdin` option, since it completely makes sense for other use cases to just show an error

**Comment by bram209** [comment]
hi, could you try the latest version (0.1.14)? I suspect this issue is related to #78

**Comment by bram209** [comment]
I will close the issue for now, if the problem persists, please don't hesitate to reopen the issue
