### ISSUE TITLE
Is there a tree-sitter grammar that can indent Leptos/"rsx" correctly?

### ISSUE THREAD

**Issue by aguynamedben** [bram209/leptosfmt#96]
Do you know if there's a tree-sitter grammar that will be able to indent Leptos `view!` macro as expected? This command is very nice as an after-save hook to clean up my "rsx", but day-to-day it's somewhat frustrating to not have my editor indent.

I use tree-sitter in Emacs and have it hooked up as good-as-possible with the [tree-sitter-rust](https://github.com/tree-sitter/tree-sitter-rust) grammar, but the same problem exists in VS Code, i.e. "Reindent lines" doesn't do the right thing.

## leptosfmt doing a good job!
<img width="616" alt="image" src="https://github.com/bram209/leptosfmt/assets/107841/b0100e79-7230-456e-b6e5-35f376c761ba">

## After letting VS Code indent
<img width="657" alt="image" src="https://github.com/bram209/leptosfmt/assets/107841/af0ffc3f-37b9-43c7-a370-b3cf49fceedc">
<img width="615" alt="image" src="https://github.com/bram209/leptosfmt/assets/107841/4906f193-a80d-4476-9332-b1adb5c3a246">

My Emacs with the Rust tree-sitter mode does a similar thing where it just doesn't know how to indent the <button> elements, even though the Rust tree-sitter grammar correctly indents other Rust code outside of the HTML-ish `view!` macro.

I wonder how difficult it would be to extend tree-sitter-rust to support the Leptos `view!` macro. 🤔

**Comment by bram209** [comment]
You can run the formatter on save to let it fix the indentation, but indention as you type is out of scope (as it's more of an editor functionality). 

Maybe (in the future) I will continue on https://github.com/bram209/leptos-language-server to see if it is possible to add this functionality. I will close this issue in favour of the discussion happening at https://github.com/leptos-rs/leptos/issues/2108
