### ISSUE TITLE
usage with other framework

### ISSUE THREAD

**Issue by jpx40** [bram209/leptosfmt#98]
Hey, can u use leptosfmt outside of leptos, for example with Sauron or yew.rs

**Comment by bram209** [comment]
hey, currently it is specifically build for the `view!` macro of leptos and is able to format `rstml` https://github.com/rs-tml/rstml compatible syntax. 

That said, with relatively little effort I could add support for other syntaxes as well and reuse components such as:
- pretty printer
- CLI & other tooling
- syn-based rust formatting (prettyplease)

I might take up on this if I have a little bit more free time.

**Comment by jpx40** [comment]
sry, i am relative new to Rust so i couldn't Really help.

**Comment by jpx40** [comment]
but i will try to Contribute

**Comment by SofusA** [comment]
This would be awesome! 
I am trying out vidhanio/hypertext for a simple htmx site which is also using rstml. 

I have aliased their rsx! macro to view! which allows leptosfmt to pick up the macro:

```
macro_rules! view {
    ($($body:tt)*) => {
        rsx_move!($($body)*)
    };
}
```

It would be awesome to be able to input a range of macros to format with the cli. 

Thanks for an awesome tool btw.
